# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c1ea9f3b3e4b3813bb345f631d9bfe6b6684e02843548141d74da2e892b82683c24b47b230baa16286e9c747cfa6ccc46aa4c248b33b650d1f7e13aefbd115b

test:
  secret_key_base: 278ccc6967c6191f9ad54e10a2f0d94b94e1670bc4dad0b92364a9fff42634b3232b692df6469f0c8ad660684ecbba61a7a00462cd2a7d96719dc67e11e57b04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
